# Generated by Django 4.1.7 on 2023-03-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='brand name')),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2000)),
                ('inventary_number', models.CharField(max_length=25, null=True)),
                ('condition', models.CharField(choices=[('GOOD', 'GOOD'), ('MEDIUM', 'MEDIUM'), ('BAD', 'BAD')], max_length=6)),
                ('entry_date', models.DateField(null=True)),
                ('title', models.FileField(null=True, upload_to='titles/')),
                ('image', models.ImageField(null=True, upload_to='cars/')),
                ('waiting', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventary.brands')),
            ],
        ),
        migrations.CreateModel(
            name='SoldCars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=10)),
                ('date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.buyers')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.cars')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='model name')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.brands')),
            ],
        ),
        migrations.CreateModel(
            name='JunkCars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('waiting', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.cars')),
            ],
        ),
        migrations.CreateModel(
            name='CarsOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_out', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.cars')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventary.models'),
        ),
    ]
