# Generated by Django 4.1.7 on 2023-03-28 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='junkcars',
            name='scratched_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='junkcars',
            name='to_junk_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(null=True, upload_to='static/cars/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='title',
            field=models.FileField(null=True, upload_to='media/titles/'),
        ),
    ]
