# Generated by Django 4.1.7 on 2023-04-26 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0002_junkcars_scratched_date_junkcars_to_junk_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='cars',
            name='title_condition',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('REBUILT', 'Rebuilt'), ('OTHER', 'Other')], default='Clean', max_length=7),
        ),
        migrations.AddField(
            model_name='cars',
            name='vin_number',
            field=models.CharField(default='00', max_length=15),
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('sale_date', models.DateField()),
                ('price', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.buyers')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventary.cars')),
            ],
        ),
    ]
